return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    opts = {
        auto_install = true,
        sync_install = true,
        ensure_installed = {
            "c",
            "cpp",
            "c_sharp",
            "lua",
            "luau",
            "vim",
            "vimdoc",
            "javascript",
            "typescript",
            "html",
            "css",
            "php",
            "python",
        },
        highlight = { enable = true },
        indent = {
            enable = true,
            additional_vim_regex_highlighting = { "markdown" },
        },
    },
}
