builtins = []
cache-dir = "~/.cache/ruff"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
fix = true
fix-only = true
include = ["*.py", "*.pyi", "*.ipynb"]
indent-width = 4
line-length = 120
namespace-packages = []
preview = false
respect-gitignore = false
show-fixes = false
target-version = "py313"
unsafe-fixes = false

extend-exclude = []
extend-include = []

[per-file-target-version]

[analyze]
detect-string-imports = true
direction = "dependencies"
exclude = []
preview = false

[analyze.include-dependencies]

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
exclude = []
indent-style = "tab"
line-ending = "lf"
preview = false
quote-style = "double"
skip-magic-trailing-comma = true

[lint]
allow-confusables = []
dummy-variable-rgx = "^_$"
exclude = []
explicit-preview-rules = true
external = []
fixable = []
ignore = ["D147"]
ignore-init-module-imports = false
logger-objects = []
preview = false
select = ["D", "E4", "E7", "E9", "F"]
task-tags = ["TODO", "FIXME", "XXX"]
typing-modules = []
unfixable = []

extend-fixable = []
extend-ignore = []
extend-safe-fixes = []
extend-select = []
extend-unsafe-fixes = []

[lint.extend-per-files-ignores]
[lint.per-file-ignores]

[lint.flake8-annotations]
allow-star-arg-any = true
ignore-fully-untyped = true
mypy-init-return = true
suppress-dummy-args = true
suppress-none-returning = true

[lint.flake8-bandit]
check-typed-exception = true
hardcoded-tmp-directory = []
hardcoded-tmp-directory-extend = []

[lint.flake8-boolean-trap]
extend-allowed-calls = []

[lint.flake8-bugbear]
extend-immutable-calls = []

[lint.flake8-builtins]
builtins-allowed-modules = []
builtins-strict-checking = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-copyright]

[lint.flake8-errmsg]
max-string-length = 0

[lint.flake8-gettext]
function-names = ["_", "gettext", "ngettext"]

extend-function-names = []

[lint.flake8-implicit-str-concat]
allow-multiline = true

[lint.flake8-import-conventions]
banned-from = []

[lint.flake8-import-conventions.aliases]
altair = "alt"
matplotlib = "mpl"
"matplotlib.pyplot" = "plt"
numpy = "np"
pandas = "pd"
scipy = "sp"
seaborn = "sns"

[lint.flake8-import-conventions.banned-aliases]
[lint.flake8-import-conventions.extend-aliases]

[lint.flake8-pytest-style]
fixture-parentheses = true
mark-parentheses = false
parametrize-names-type = "list"
parametrize-values-row-type = "tuple"
parametrize-values-type = "list"
raises-require-match-for = []
warns-require-match-for = []

raises-extend-require-match-for = []
warns-extend-require-match-for = []

[lint.flake8-quotes]
avoid-escape = false
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[lint.flake8-self]
ignore_names = [
    "_make",
    "_asdict",
    "_replace",
    "_fields",
    "_field_defaults",
    "_name_",
    "_value_",
]

extend-ignore-names = []

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"
banned-module-level-imports = []

[lint.flake8-tidy-imports.banned-api]

[lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]
quote-annotations = true
runtime-evaluated-base-classes = [
    "pydantic.BaseModel",
    "sqlalchemy.orm.DeclarativeBase",
]
strict = true

[lint.flake8-unused-arguments]
ignore-variadic-names = false

[lint.isort]
case-sensitive = true
classes = []
combine-as-imports = true
constants = []
default-section = "third-party"
detect-same-package = false
extra-standard-library = []
force-single-line = true
force-sort-within-sections = true
force-to-top = []
force-wrap-aliases = true
forced-seperate = []
from-first = true
known-first-party = []
known-local-folder = []
known-third-party = []
length-sort = false
length-sort-straight = false
lines-after-imports = 1
lines-between-types = 1
no-lines-before = []
no-sections = false
order-by-type = true
relative-imports-order = "closest-to-furthest"
required-imports = []
section-order = [
    "future",
    "standard-library",
    "first-party",
    "local-folder",
    "third-party",
]
single-line-exclusions = []
split-on-trailing-comma = true
variables = []

[lint.isort.sections]
"django" = ["django"]

[lint.mccabe]
max-complexity = 10

[lint.pep8-naming]
classmethod-decorators = []
ignore-names = [
    "setUp",
    "tearDown",
    "setUpClass",
    "tearDownClass",
    "setUpModule",
    "tearDownModule",
    "asyncSetUp",
    "asyncTearDown",
    "setUpTestData",
    "failureException",
    "longMessage",
    "maxDiff",
]
staticmethod-decorators = []

extend-ignore-names = []

[lint.pycodestyle]
ignore-overlong-task-comments = false
max-doc-length = 120
max-line-length = 150

[lint.pydoclint]
ignore-one-line-docstrings = false
convention = "google"
ignore-decorators = []
ignore-var-parameters = false
property-decorators = []

[lint.pyflakes]
allowed-unused-imports = []
extend-generics = []

[lint.pylint]
allow-dunder-method-names = []
allow-magic-value-types = ["str", "bytes", "int"]
max-args = 5
max-bool-expr = 5
max-branches = 10
max-locals = 15
max-nested-blocks = 5
max-positional-args = 5
max-public-methods = 30
max-returns = 5
max-statements = 100

[lint-pyupgrade]
keep-runtime-typing = true

[lint.ruff]
allowed-markup-calls = []
extend-markup-names = []
parenthesize-tuple-in-subscript = false
